# Usar la imagen oficial de PostgreSQL
FROM postgres:latest

# Establecer variables de entorno para PostgreSQL
ENV POSTGRES_DB=reddragonclub_db
ENV POSTGRES_USER=reddragon
ENV POSTGRES_PASSWORD=reddragon1234+

# Exponer el puerto 5432
EXPOSE 5432
